In [2]:
import pandas as pd

In [3]:
import pandas as pd

# Student Data
data = {
    "Name": ["Rohit", "Amit", "Priya", "Sneha", "Rahul"],
    "Age": [20, 21, 19, 20, 22],
    "City": ["Pune", "Mumbai", "Nashik", "Nagpur", "Kolhapur"],
    "Marks": [85, 78, 92, 88, 75]
}

# Create DataFrame
students = pd.DataFrame(data)

print("Student DataFrame:")
students

Student DataFrame:

    Name  Age      City  Marks
0  Rohit   20      Pune     85
1   Amit   21    Mumbai     78
2  Priya   19    Nashik     92
3  Sneha   20    Nagpur     88
4  Rahul   22  Kolhapur     75

In [4]:
students.to_csv("students.csv", index=False)

print("CSV file saved successfully.")

CSV file saved successfully.

In [5]:
loaded_data = pd.read_csv("students.csv")

print("Loaded Data:")
loaded_data

Loaded Data:

    Name  Age      City  Marks
0  Rohit   20      Pune     85
1   Amit   21    Mumbai     78
2  Priya   19    Nashik     92
3  Sneha   20    Nagpur     88
4  Rahul   22  Kolhapur     75

In [6]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [7]:
import pandas as pd

data = {
    "Name": ["Rohit", "Amit"],
    "Marks": [85, 90]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks
0  Rohit     85
1   Amit     90

In [8]:
import pandas as pd

student = {
    "Name": ["Rohit", "Amit", "Priya"],
    "Age": [20, 21, 19],
    "Marks": [85, 78, 92]
}

df = pd.DataFrame(student)

print(df)

    Name  Age  Marks
0  Rohit   20     85
1   Amit   21     78
2  Priya   19     92

In [ ]:
# Pandas Assignment 1

## Theory Answers

### Q1. What is Pandas?

**Answer:**

Pandas is a Python library used for data analysis and data manipulation. It provides powerful data structures like **Series** and **DataFrame** for handling structured data.

---

### Q2. Why is Pandas used in AI/ML?

**Answer:**

Pandas is used in AI and Machine Learning because it helps to:

- Read datasets (CSV, Excel, SQL, etc.)
- Clean missing data
- Filter and sort data
- Analyze datasets
- Prepare data before training ML models

---

### Q3. What is a Series?

**Answer:**

A **Series** is a one-dimensional labeled array in Pandas. It stores data in a single column.

---

### Q4. What is a DataFrame?

**Answer:**

A **DataFrame** is a two-dimensional table with rows and columns. It is the most commonly used data structure in Pandas.

---

### Q5. What is a CSV File?

**Answer:**

CSV stands for **Comma-Separated Values**. It is a file format used to store tabular data where each value is separated by a comma.

---

### Q6. Write a program to create a DataFrame from a dictionary.

```python
import pandas as pd

student = {
    "Name": ["Rohit", "Amit", "Priya"],
    "Age": [20, 21, 19],
    "Marks": [85, 78, 92]
}

df = pd.DataFrame(student)
print(df)
```