In [1]:
import pandas as pd

In [2]:
# Employee Data

data = {
    "Employee ID": [101, 102, 103, 104, 105],
    "Name": ["Rohit", "Amit", "Priya", "Sneha", "Rahul"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing"],
    "Salary": [45000, 38000, 55000, 42000, 60000],
    "City": ["Pune", "Mumbai", "Pune", "Nagpur", "Pune"]
}

employee = pd.DataFrame(data)

print("Employee DataFrame")
employee

Employee DataFrame

   Employee ID   Name Department  Salary    City
0          101  Rohit         IT   45000    Pune
1          102   Amit         HR   38000  Mumbai
2          103  Priya    Finance   55000    Pune
3          104  Sneha         IT   42000  Nagpur
4          105  Rahul  Marketing   60000    Pune

In [3]:
print("First 3 Rows")
employee.head(3)

First 3 Rows

   Employee ID   Name Department  Salary    City
0          101  Rohit         IT   45000    Pune
1          102   Amit         HR   38000  Mumbai
2          103  Priya    Finance   55000    Pune

In [4]:
print("Last 2 Rows")
employee.tail(2)

Last 2 Rows

   Employee ID   Name Department  Salary    City
3          104  Sneha         IT   42000  Nagpur
4          105  Rahul  Marketing   60000    Pune

In [5]:
print("Dataset Shape")
print(employee.shape)

Dataset Shape
(5, 5)

In [6]:
print("Column Names")
print(employee.columns)

Column Names
Index(['Employee ID', 'Name', 'Department', 'Salary', 'City'], dtype='str')

In [7]:
print("Employees with Salary Greater Than 40000")

employee[employee["Salary"] > 40000]

Employees with Salary Greater Than 40000

   Employee ID   Name Department  Salary    City
0          101  Rohit         IT   45000    Pune
2          103  Priya    Finance   55000    Pune
3          104  Sneha         IT   42000  Nagpur
4          105  Rahul  Marketing   60000    Pune

In [8]:
print("Employees from Pune")

employee[employee["City"] == "Pune"]

Employees from Pune

   Employee ID   Name Department  Salary  City
0          101  Rohit         IT   45000  Pune
2          103  Priya    Finance   55000  Pune
4          105  Rahul  Marketing   60000  Pune

In [ ]:
# Pandas Assignment 2

## Theory Answers

### Q1. What is the purpose of head()?

**Answer:**

The **head()** function displays the first 5 rows of a DataFrame by default. We can specify the number of rows using `head(n)`.

---

### Q2. What is the purpose of tail()?

**Answer:**

The **tail()** function displays the last 5 rows of a DataFrame by default. We can specify the number of rows using `tail(n)`.

---

### Q3. What does shape return?

**Answer:**

The **shape** attribute returns the number of rows and columns in a DataFrame as a tuple `(rows, columns)`.

---

### Q4. What does info() display?

**Answer:**

The **info()** method displays information about the DataFrame such as:
- Number of rows and columns
- Column names
- Data types
- Non-null values
- Memory usage

---

### Q5. What does describe() display?

**Answer:**

The **describe()** method displays statistical information such as:
- Count
- Mean
- Standard Deviation
- Minimum Value
- Maximum Value
- 25%, 50%, and 75% percentiles