In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create Student DataFrame with missing values and duplicate record

data = {
    "Name": ["Rohit", "Amit", "Priya", "Sneha", "Rahul", "Amit"],
    "Age": [20, np.nan, 19, 21, np.nan, np.nan],
    "Marks": [85, 78, np.nan, 90, 88, 78],
    "City": ["Pune", "Mumbai", "Nashik", "Nagpur", "Pune", "Mumbai"]
}

students = pd.DataFrame(data)

print("Original DataFrame")
students

Original DataFrame

    Name   Age  Marks    City
0  Rohit  20.0   85.0    Pune
1   Amit   NaN   78.0  Mumbai
2  Priya  19.0    NaN  Nashik
3  Sneha  21.0   90.0  Nagpur
4  Rahul   NaN   88.0    Pune
5   Amit   NaN   78.0  Mumbai

In [3]:
print("Missing Values")

students.isnull()

Missing Values

    Name    Age  Marks   City
0  False  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False  False
4  False   True  False  False
5  False   True  False  False

In [4]:
print("Count of Missing Values")

students.isnull().sum()

Count of Missing Values

Name     0
Age      3
Marks    1
City     0
dtype: int64

In [5]:
print("Replace Missing Values with 0")

students.fillna(0)

Replace Missing Values with 0

    Name   Age  Marks    City
0  Rohit  20.0   85.0    Pune
1   Amit   0.0   78.0  Mumbai
2  Priya  19.0    0.0  Nashik
3  Sneha  21.0   90.0  Nagpur
4  Rahul   0.0   88.0    Pune
5   Amit   0.0   78.0  Mumbai

In [6]:
print("Replace Missing Age with Average Age")

average_age = students["Age"].mean()

students["Age"] = students["Age"].fillna(average_age)

students

Replace Missing Age with Average Age

    Name   Age  Marks    City
0  Rohit  20.0   85.0    Pune
1   Amit  20.0   78.0  Mumbai
2  Priya  19.0    NaN  Nashik
3  Sneha  21.0   90.0  Nagpur
4  Rahul  20.0   88.0    Pune
5   Amit  20.0   78.0  Mumbai

In [7]:
print("Duplicate Records")

students.duplicated()

Duplicate Records

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [8]:
print("Duplicate Rows")

students[students.duplicated()]

Duplicate Rows

   Name   Age  Marks    City
5  Amit  20.0   78.0  Mumbai

In [9]:
print("Remove Duplicate Records")

students = students.drop_duplicates()

students

Remove Duplicate Records

    Name   Age  Marks    City
0  Rohit  20.0   85.0    Pune
1   Amit  20.0   78.0  Mumbai
2  Priya  19.0    NaN  Nashik
3  Sneha  21.0   90.0  Nagpur
4  Rahul  20.0   88.0    Pune

In [10]:
print("DataFrame Information")

students.info()

DataFrame Information
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      float64
 2   Marks   4 non-null      float64
 3   City    5 non-null      str
dtypes: float64(2), str(2)
memory usage: 292.0 bytes

In [11]:
print("Statistical Summary")

students.describe()

Statistical Summary

             Age      Marks
count   5.000000   4.000000
mean   20.000000  85.250000
std     0.707107   5.251984
min    19.000000  78.000000
25%    20.000000  83.250000
50%    20.000000  86.500000
75%    20.000000  88.500000
max    21.000000  90.000000

In [ ]:
# Pandas Assignment 3

## Theory Answers

### Q1. What is Data Cleaning?

**Answer:**

Data Cleaning is the process of identifying and correcting inaccurate, incomplete, duplicate, or missing data to improve data quality before analysis.

---

### Q2. What is a Missing Value?

**Answer:**

A missing value is a value that is not available in a dataset. In Pandas, missing values are represented as **NaN (Not a Number)**.

---

### Q3. What is the purpose of isnull()?

**Answer:**

The **isnull()** method is used to detect missing values in a DataFrame. It returns **True** for missing values and **False** for non-missing values.

---

### Q4. What is the purpose of fillna()?

**Answer:**

The **fillna()** method replaces missing values with a specified value such as **0**, **mean**, **median**, or any custom value.

---

### Q5. What is the difference between fillna() and dropna()?

**Answer:**

- **fillna()** replaces missing values with a specified value.
- **dropna()** removes rows or columns containing missing values.

---

### Q6. What is the purpose of drop_duplicates()?

**Answer:**

The **drop_duplicates()** method removes duplicate rows from a DataFrame and keeps only unique records.