In [1]:
import pandas as pd

In [2]:
# Employee Data

data = {
    "Name": ["Rohit", "Amit", "Priya", "Sneha", "Rahul", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing", "HR"],
    "Salary": [45000, 38000, 55000, 42000, 60000, 40000]
}

employee = pd.DataFrame(data)

print("Employee DataFrame")
employee

Employee DataFrame

    Name Department  Salary
0  Rohit         IT   45000
1   Amit         HR   38000
2  Priya    Finance   55000
3  Sneha         IT   42000
4  Rahul  Marketing   60000
5   Neha         HR   40000

In [3]:
print("Salary in Ascending Order")

employee.sort_values(by="Salary", ascending=True)

Salary in Ascending Order

    Name Department  Salary
1   Amit         HR   38000
5   Neha         HR   40000
3  Sneha         IT   42000
0  Rohit         IT   45000
2  Priya    Finance   55000
4  Rahul  Marketing   60000

In [4]:
print("Salary in Descending Order")

employee.sort_values(by="Salary", ascending=False)

Salary in Descending Order

    Name Department  Salary
4  Rahul  Marketing   60000
2  Priya    Finance   55000
0  Rohit         IT   45000
3  Sneha         IT   42000
5   Neha         HR   40000
1   Amit         HR   38000

In [5]:
print("Unique Departments")

employee["Department"].unique()

Unique Departments

<StringArray>
['IT', 'HR', 'Finance', 'Marketing']
Length: 4, dtype: str

In [6]:
print("Employee Count in Each Department")

employee["Department"].value_counts()

Employee Count in Each Department

Department
IT           2
HR           2
Finance      1
Marketing    1
Name: count, dtype: int64

In [7]:
print("Average Salary of Each Department")

employee.groupby("Department")["Salary"].mean()

Average Salary of Each Department

Department
Finance      55000.0
HR           39000.0
IT           43500.0
Marketing    60000.0
Name: Salary, dtype: float64

In [8]:
print("Maximum Salary of Each Department")

employee.groupby("Department")["Salary"].max()

Maximum Salary of Each Department

Department
Finance      55000
HR           40000
IT           45000
Marketing    60000
Name: Salary, dtype: int64

In [9]:
print("DataFrame Information")

employee.info()

DataFrame Information
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Salary      6 non-null      int64
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [10]:
print("Statistical Summary")

employee.describe()

Statistical Summary

             Salary
count      6.000000
mean   46666.666667
std     8846.845012
min    38000.000000
25%    40500.000000
50%    43500.000000
75%    52500.000000
max    60000.000000

In [11]:
# Pandas Assignment 4

## Theory Answers

### Q1. What is the purpose of sort_values()?

**Answer:**

The **sort_values()** method is used to sort the rows of a DataFrame based on one or more columns in ascending or descending order.

---

### Q2. What is the difference between ascending and descending sorting?

**Answer:**

- **Ascending Sorting:** Arranges data from smallest to largest (A to Z or 0 to 9).
- **Descending Sorting:** Arranges data from largest to smallest (Z to A or 9 to 0).

---

### Q3. What is the purpose of unique()?

**Answer:**

The **unique()** method returns all unique values from a column by removing duplicate values.

---

### Q4. What is the purpose of value_counts()?

**Answer:**

The **value_counts()** method counts the frequency of each unique value in a column.

---

### Q5. What is groupby()?

**Answer:**

The **groupby()** method groups rows that have the same values in a column and allows operations like **sum, mean, max, min, and count** on each group.

---

### Q6. Write the aggregation functions available in Pandas.

**Answer:**

Some commonly used aggregation functions are:

- sum()
- mean()
- max()
- min()
- count()
- median()
- std()
- var()

SyntaxError: invalid syntax (77573286.py, line 7)

In [12]:
print("Aggregation Functions")

print("Sum of Salary:")
print(employee["Salary"].sum())

print("\nAverage Salary:")
print(employee["Salary"].mean())

print("\nMaximum Salary:")
print(employee["Salary"].max())

print("\nMinimum Salary:")
print(employee["Salary"].min())

print("\nCount of Employees:")
print(employee["Salary"].count())

Aggregation Functions
Sum of Salary:
280000

Average Salary:
46666.666666666664

Maximum Salary:
60000

Minimum Salary:
38000

Count of Employees:
6